### ISSUE TITLE
Use cases: interoperate or parallel records for credit history?

### ISSUE THREAD

**Issue by du5t** [WebOfTrustInfo/rebooting-the-web-of-trust#48]
There are two competing narratives for the use case of an insufficiently-credentialed person trying to get a bank account and participate in a Western credit system (FICO, renting housing, traditional loans).

One narrative is about using verifiable claims to enable the person's entry into the traditional system, the other one is about setting up a parallel infrastructure that invites servicers to move to an independent infrastructure.

Which should the white paper discuss? We risk confusing the reader if we mix them up in the middle of an otherwise similar situation.

**Comment by jimscarver** [comment]
Between the traditional banking circles and humans liberated to be their own bank, thanks to bitcoin, establishing global trust for the individual, are the credit unions, as in  http://MoneyCircles.com social money dynamical webs of trust constructed P2P.

**Comment by du5t** [comment]
Credit unions definitely are a different model from banks, but they're perceived as similar from the perspective of consumer offerings (UX is everything for B2C). We want to be able to offer a less-contentious option as well as a radical one so that readers feel like they were shown something they can agree with either way.

What I'll do for now is place the more radical model in the context of a user with a less hegemonic banking system (i.e., non-G20), and let the reader make up their mind.

Expect a barrage of commits soon.

**Comment by du5t** [comment]
The hybrid approach is present in the main repo, for your perusal: https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/blob/master/draft-documents/satisfying-real-world-use-cases.md

**Comment by du5t** [comment]
Closing since paper was published.
