### ISSUE TITLE
use cases: Is your offering represented?

### ISSUE THREAD

**Issue by du5t** [WebOfTrustInfo/rebooting-the-web-of-trust#49]
Once we have an acceptable editor-ready draft (probably by midnight PDT tonight), I want to invite everyone to inspect sections where technologies or brands are referenced as examples of systems that meet at least some of the needs illustrated in a use case, and submit PRs inserting links as needed.

Let's make sure everyone's efforts are "discoverable" :)

**Comment by jimscarver** [comment]
I believe, in the longer term, we should crowd source use cases.  The list so far seems weak.  We should mention anything relevant to our global mission as well as our particular offering.  Things like blockchain providence, user managed authorization and social money should not be excluded.  There should be examples answering most everyone's concerns.  e.g. 

MoneyCircles.com https://docs.google.com/document/d/1epCi7EURf3fc2S-e7QSj6ORyDOUXvFybeyBIhmITA2Y/edit
In the future we will pool assets with families, friends, and other organizations.  We are no longer dependent of the currencies of the obligatory.  Do we dare including that use case?

FreeTrust.org is my interest, a collaboration comprehensive approach to machine augmented trustworthy cyberspace with complete freedom of trust. https://docs.google.com/document/d/1HF5iEVaVWzrYjqGNuKfy00EEtrjBnRsTvBKvKCmQW0g/edit

Comments in those documents would be appreciated.

**Comment by du5t** [comment]
I'd say throughout the designshop everyone was completely open to input from anyone about what ended up in the paper. We simply picked a representative range that people were willing to work on--[the main authors](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust/issues/53#issuecomment-155152473) of this paper have expended a costly amount of effort on each one, and the effort required to edit a document to have uniform composition rises steeply with the number of large contributions.

While I think that the applications and platforms you mention above are valid and needed, the stated goal of the paper from the outset was to proceed from non-contentious, recognized needs that already exist, and then discuss how those needs could be met from within the sector. A technology that meets an existing strongly recognized need (such as credentialing for the stateless) reads much better than a solution that could be dismissed as looking for a problem.

If we can do well with this paper, we can always build from there.

**Comment by du5t** [comment]
Closing since paper was published.
